#include <stdio.h>
#include "visualLB.h"
#include "LBDefinitions.h"
#include "helper.h"
#include "computeCellValues.h"

#define BSIZE 80


void write_vtkHeader( FILE *fp, int xlength ) {
  if( fp == NULL )  {
    char szBuff[BSIZE];
    sprintf( szBuff, "Null pointer in write_vtkHeader" );
    ERROR( szBuff );
    return;
  }

  fprintf(fp,"# vtk DataFile Version 2.0\n");
  fprintf(fp,"generated by CFD-lab course output \n");
  fprintf(fp,"ASCII\n");
  fprintf(fp,"\n");
  fprintf(fp,"DATASET STRUCTURED_GRID\n");
  fprintf(fp,"DIMENSIONS  %i %i %i \n", xlength, xlength, xlength);
  fprintf(fp,"POINTS %i float\n", CUBE(xlength) );
  fprintf(fp,"\n");
}


void write_vtkPointCoordinates( FILE *fp, int xlength) {

	unsigned long x, y, z;

	/* set the coordinates in a unit cube */

	for( z = 1ul; z < xlength+1; z++)
	  for(y = 1ul; y < xlength+1; y++)
		  for( x = 1ul; x < xlength+1; x++)
				  fprintf(fp, "%f %f %f\n", (double)(x-1)/(xlength-1), (double)(y-1)/(xlength-1), (double)(z-1)/(xlength-1) );

}




void writeVtkOutput(const double * const collideField, const int * const flagField, const char * filename, unsigned int t, int xlength) {

	unsigned long x, y, z;
	double density, velocity[DIM];
	char szFileName[BSIZE];
	FILE *fp=NULL;

	sprintf( szFileName, "%s.%i.vtk", filename, t );
	fp = fopen( szFileName, "w");
	if( fp == NULL ){
		char szBuff[BSIZE];
		sprintf( szBuff, "Failed to open %s", szFileName );
		ERROR( szBuff );
		return;
	}

	write_vtkHeader( fp, xlength);
	write_vtkPointCoordinates(fp, xlength);

	fprintf(fp,"POINT_DATA %i \n", CUBE(xlength) );

	fprintf(fp,"\n");
	fprintf(fp, "VECTORS velocity float\n");


	for(z=1ul; z < xlength+1; z++)
		for( y=1ul; y < xlength+1; y++)
			for(x=1ul; x < xlength+1; x++){
				double const * const currentCell = collideField + Q * (x + (xlength+2) * y + SQ(xlength+2) * z);

				computeDensity(currentCell, &density);
				computeVelocity(currentCell, &density, velocity);
				fprintf(fp, "%f %f %f\n", velocity[0], velocity[1], velocity[2]);
			}

	fprintf(fp,"\n");
	fprintf(fp,"CELL_DATA %i \n", CUBE(xlength-1) );
	fprintf(fp, "SCALARS density float 1 \n");
	fprintf(fp, "LOOKUP_TABLE default \n");
	for(z=2ul; z < xlength+1; z++)
		for(y=2ul; y < xlength+1; y++)
			for(x=2ul; x < xlength+1; x++){
				double const * const currentCell = collideField + Q * (x + (xlength+2) * y + SQ(xlength+2) * z);

				computeDensity(currentCell, &density);
				fprintf(fp, "%f\n", density );
			}



	if( fclose(fp) )
	{
		char szBuff[BSIZE];
		sprintf( szBuff, "Failed to close %s", szFileName );
		ERROR( szBuff );
	}


}
